services:
  - type: web
    name: runwithkam
    env: node
    plan: free
    region: oregon
    buildCommand: npm ci
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: TZ
        value: America/New_York
    healthCheckPath: /api/health
